name: Build and Deploy to Build Repository

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Setup SSH key for build repository
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.BUILD_REPO_DEPLOY_KEY }}

      - name: Checkout build repository
        uses: actions/checkout@v4
        with:
          repository: lorenzboss/jazz-worktime-build
          ssh-key: ${{ secrets.BUILD_REPO_DEPLOY_KEY }}
          path: build-repo

      - name: Clear build repository (optional)
        run: |
          cd build-repo
          # Lösche alle Dateien außer .git
          find . -not -path './.git*' -delete

      - name: Copy build artifacts
        run: |
          # Kopiere die Build-Outputs in den dist Ordner (Structure beibehalten)
          mkdir -p build-repo/dist
          cp -r dist/* build-repo/dist/

          # Kopiere das manifest.json unverändert
          cp manifest.json build-repo/

          # Erstelle ein README für das Build-Repository mit dynamischen Infos
          cat > build-repo/README.md << EOF
          # Jazz Worktime Build

          This repository contains the built version of the Jazz Worktime browser extension.

          **Source Code:** [lorenzboss/jazz-worktime](https://github.com/lorenzboss/jazz-worktime)
          **Built from commit:** [\`${GITHUB_SHA:0:7}\`](https://github.com/lorenzboss/jazz-worktime/commit/${GITHUB_SHA})
          **Build date:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')

          ## Installation

          1. Download or clone this repository
          2. Open Chrome/Edge and go to \`chrome://extensions/\`
          3. Enable "Developer mode"
          4. Click "Load unpacked" and select this folder

          ## About

          This build is automatically generated from the source repository.
          For development, issues, and contributions, please visit the source repository.
          EOF

      - name: Commit and push to build repository
        run: |
          cd build-repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto-build from $(date)"
            git push
          else
            echo "No changes to commit"
          fi
